name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

    - name: Build the tagged image
      run: docker build . --file Dockerfile --tag coleusapp/frontend:${{steps.vars.outputs.tag}}

    - name: Push the tagged image
      run: docker push coleusapp/frontend:${{steps.vars.outputs.tag}}

    - name: Build the latest image
      run: docker build . --file Dockerfile --tag coleusapp/frontend:latest

    - name: Push the latest image
      run: docker push coleusapp/frontend:latest

